### ISSUE TITLE
Create radio buttons in add seating that toggle between standing room and seated options. 

### ISSUE THREAD

**Issue by DennisVargas** [WSUVCapstoneTeam7/SeatMapMaker#17]
Rather than Add Seating we should have Add Object -> Dropdown { seating, standing room, tables}

**Comment by DennisVargas** [comment]
An example of what I was thinking 
https://codepen.io/svnt/pen/beEgre

**Comment by DennisVargas** [comment]
This feature turned into radio buttons that select between seated and standing room.

**Comment by DennisVargas** [comment]
Seated option could work as default however when the "standing" or "general area" is selected, then the form hides the column and row sections and the submit button sends the title field into the createGeneralArea() function (may not be actual name; just psedocode).

**Comment by amyphillips-wsuv** [comment]
I got radio buttons working for tables (button for round tables shows one text box for number of seats, button for rectangle shows x- and y-axis options), so I should be able to add them here for this functionality. But I'm going to put my two cents in and say it doesn't make sense to me for "standing area" to be an option under "seating area". I can understand wanting a difference between general and standing since tickets can be purchased for standing. But I'm not sure creating standing area under a seating area menu makes sense because you're not seated. If it's what you guys want to do though, getting the radio button menu switch thing was really easy to implement once I found out how it was supposed to be done.

**Comment by DennisVargas** [comment]
Sounds good, the radio buttons aren't necessary to anything; it was an idea that was half implemented and needed to be either removed or fully realized. I'm fine with removing them they don't serve any purpose. We can close this issue once the radio buttons are gone.

**Comment by amyphillips-wsuv** [comment]
I confirmed with Tyler that he's working on this so I'm removing myself.

**Comment by DennisVargas** [comment]
@amyphillips-wsuv I mostly was trying to add everyone to the conversation which I found is possible by mentioning them using the "@username" keyword inside a comment. @cfeener this should add chris to the conversation but not assign him, theoretically.
